TwitchEmotes_Baddies_Emoticons = {
    ["Crungo"] = "Crungo",
    ["sputSussy"] = "sputSussy",
    ["OhSnap"] = "OhSnap",
    ["mhm"] = "mhm",
    ["GLORPSHIT"] = "GLORPSHIT",
    ["Shoo"] = "Shoo",
    ["NOOOO"] = "NOOOO",
    ["yippee"] = "yippee",
    ["clappi"] = "clappi",
    ["Shrug"] = "Shrug",
    ["splort"] = "splort",
    ["ReallyMad"] = "ReallyMad",
    ["DOESHEKNOW"] = "DOESHEKNOW",
    ["DEAL"] = "DEAL",
    ["doid"] = "doid",
    ["SadCatClown"] = "SadCatClown",
    ["FRICK"] = "FRICK",
    ["CEASE"] = "CEASE",
    ["sputWide"] = "sputWide",
    ["lookUp"] = "lookUp",
    ["lookDown"] = "lookDown",
    ["CRIKEN"] = "CRIKEN",
    ["SoyR"] = "SoyR",
    ["WHOLETHIMCOOK"] = "WHOLETHIMCOOK",
    ["THESTAFF"] = "THESTAFF",
    ["devious"] = "devious",
    ["RightThere"] = "RightThere",
    ["LetMeIn"] = "LetMeIn",
    ["CatAHomie"] = "CatAHomie",
    ["LockedIn"] = "LockedIn",
    ["AAAA"] = "AAAA",
    ["petbabey"] = "petbabey",
    ["babey"] = "babey",
    ["WAGWHA"] = "WAGWHA",
    ["Sigh"] = "Sigh",
    ["pregWan"] = "pregWan",
    ["OneGuy"] = "OneGuy",
    ["o7"] = "o7",
    ["mweee"] = "mweee",
    ["Lurkin"] = "Lurkin",
    ["glorpWide"] = "glorpWide",
    ["glorpOff"] = "glorpOff",
    ["catFU"] = "catFU",
    ["FeelsPeonMan"] = "FeelsPeonMan",
    ["FOOTMEN"] = "FOOTMEN",
    ["Illident"] = "Illident",
    ["yummers"] = "yummers",
    ["Zuggers"] = "Zuggers",
    ["mekkaNerdge"] = "mekkaNerdge",
    ["nothKEK"] = "nothKEK",
    ["ligCraft"] = "ligCraft",
    ["wingsCozy"] = "wingsCozy",
    ["FloorDragon"] = "FloorDragon",
    ["deadJeb"] = "deadJeb",
    ["kaneiTea"] = "kaneiTea",
    ["meowchNya"] = "meowchNya",
    ["razorBrewmaster"] = "razorBrewmaster",
    ["landrickTank"] = "landrickTank",
    ["kromSummon"] = "kromSummon",
    ["tifCheer"] = "tifCheer",
    ["WAITWAITWAIT"] = "WAITWAITWAIT",
    ["GAGAGA"] = "GAGAGA",
    ["glorpDH"] = "glorpDH",
    ["glorpDK"] = "glorpDK",
    ["glorpDR"] = "glorpDR",
    ["glorpDrakB"] = "glorpDrakB",
    ["glorpDrakG"] = "glorpDrakG",
    ["glorpDrakR"] = "glorpDrakR",
    ["glorpDrakY"] = "glorpDrakY",
    ["glorpDruid"] = "glorpDruid",
    ["glorpEle"] = "glorpEle",
    ["glorpMage"] = "glorpMage",
    ["glorpPriest"] = "glorpPriest",
    ["glorpRogue"] = "glorpRogue",
    ["glorpWarlock"] = "glorpWarlock",
    ["glorpWarrior"] = "glorpWarrior",
    ["hiii"] = "hiii",
    ["byeee"] = "byeee",
    ["feaky"] = "feaky",
    ["Deplete"] = "Deplete",
    ["mee"] = "mee",
    ["Tastyge"] = "Tastyge",
    ["IRIE"] = "IRIE",
    ["WAGWAN"] = "WAGWAN",
    ["lildans"] = "lildans",
    ["StoryTime"] = "StoryTime",
    ["GIGATAUREN"] = "GIGATAUREN",
    ["blalalatath"] = "blalalatath",
    ["JAMMIES"] = "JAMMIES",
    ["Joel"] = "Joel",
    ["poggSpin"] = "poggSpin",
    ["HotBois"] = "HotBois",
    ["POGWAN"] = "POGWAN",
    ["SCATTER"] = "SCATTER",
    ["alooo"] = "alooo",
    ["bejj"] = "bejj",
    ["blushh"] = "blushh",
    ["bukWide"] = "bukWide",
    ["businejj"] = "businejj",
    ["CHARBORG"] = "CHARBORG",
    ["charboWide"] = "charboWide",
    ["chatWide"] = "chatWide",
    ["cheifWide"] = "cheifWide",
    ["cozii"] = "cozii",
    ["crikWide"] = "crikWide",
    ["Egads"] = "Egads",
    ["ezz"] = "ezz",
    ["fishh"] = "fishh",
    ["fricc"] = "fricc",
    ["blesss"] = "blesss",
    ["goodd"] = "goodd",
    ["hugg"] = "hugg",
    ["Joelver"] = "Joelver",
    ["Cupcake"] = "Cupcake",
    ["nise"] = "nise",
    ["nohear"] = "nohear",
    ["nolook"] = "nolook",
    ["notnise"] = "notnise",
    ["pizz"] = "pizz",
    ["poutt"] = "poutt",
    ["Purge"] = "Purge",
    ["sitt"] = "sitt",
    ["Sludge"] = "Sludge",
    ["staree"] = "staree",
    ["tink"] = "tink",
    ["wikked"] = "wikked",
    ["woboWide"] = "woboWide",
    ["workWork"] = "workWork",
    ["Wormtongue"] = "Wormtongue",
    ["awaree"] = "awaree",
    ["chadd"] = "chadd",
    ["charboDance"] = "charboDance",
    ["crikWalk"] = "crikWalk",
    ["CYBERBULLYING"] = "CYBERBULLYING",
    ["danse"] = "danse",
    ["dramaa"] = "dramaa",
    ["EvilJoel"] = "EvilJoel",
    ["ewLeague"] = "ewLeague",
    ["GAMBAADDICT"] = "GAMBAADDICT",
    ["wowTime"] = "wowTime",
    ["GIGACHAR"] = "GIGACHAR",
    ["GIGADEAD"] = "GIGADEAD",
    ["gigl"] = "gigl",
    ["glorpArrive"] = "glorpArrive",
    ["glorpLeave"] = "glorpLeave",
    ["GNOMED"] = "GNOMED",
    ["HyperRollCAT"] = "HyperRollCAT",
    ["notee"] = "notee",
    ["oljj"] = "oljj",
    ["ono"] = "ono",
    ["panicc"] = "panicc",
    ["PeakPls"] = "PeakPls",
    ["peepoArrive"] = "peepoArrive",
    ["peepoLate"] = "peepoLate",
    ["peepoLeave"] = "peepoLeave",
    ["peepoTalk"] = "peepoTalk",
    ["Poor"] = "Poor",
    ["riott"] = "riott",
    ["scrajj"] = "scrajj",
    ["singg"] = "singg",
    ["Summoning"] = "Summoning",
    ["taurenPls"] = "taurenPls",
    ["theyWorm"] = "theyWorm",
    ["tuckk"] = "tuckk",
    ["verypogg"] = "verypogg",
    ["woww"] = "woww",
    ["DESKCHAN"] = "DESKCHAN",
    ["PROGGERS"] = "PROGGERS",
    ["Gludge"] = "Gludge",
    ["PLACE"] = "PLACE",
    ["ewwLeague"] = "ewwLeague",
    ["Muted"] = "Muted",
    ["LL"] = "LL",
    ["HACKERMAN"] = "HACKERMAN",
    ["happ"] = "happ",
    ["owo7"] = "owo7",
    ["hehe"] = "hehe",
    ["nothBoom"] = "nothBoom",
    ["zhikDevious"] = "zhikDevious",
    ["thorGuildLead"] = "thorGuildLead",
    ["aivyHOA"] = "aivyHOA",
    ["ayaCorpa"] = "ayaCorpa",
    ["harperPuppy"] = "harperPuppy",
    ["milliyBadCall"] = "milliyBadCall",
    ["ryaiuBenched"] = "ryaiuBenched",
    ["ryaiuUnbenched"] = "ryaiuUnbenched",
    ["triskHeals"] = "triskHeals",
    ["mekkaGun"] = "mekkaGun",
    ["henrySCREECH"] = "henrySCREECH",
    ["SamFREAKY1"] = "SamFREAKY1",
    ["Melons"] = "Melons",
    ["sputMelonsWide"] = "sputMelonsWide",
    ["fu"] = "fu",
    ["ooBLEH"] = "ooBLEH",
    ["AINTNOWAY"] = "AINTNOWAY",
    [""] = "",
}

TwitchEmotes_Baddies_Emoticons_Pack = {
    ["Crungo"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Crungo.tga:28:28",
    ["sputSussy"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\sputSussy.tga:",
    ["OhSnap"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\OhSnap.tga",
    ["mhm"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\mhm.tga",
    ["GLORPSHIT"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\GLORPSHIT.tga",
    ["Shoo"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Shoo.tga",
    ["NOOOO"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\NOOOO.tga",
    ["yippee"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\yippee.tga",
    ["clappi"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\clappi.tga",
    ["Shrug"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Shrug.tga:28:28",
    ["splort"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\splort.tga:32:46",
    ["ReallyMad"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\ReallyMad.tga:28:28",
    ["DOESHEKNOW"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\DOESHEKNOW.tga:28:28",
    ["DEAL"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\DEAL.tga:32:96",
    ["doid"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\doid.tga:24:27",
    ["SadCatClown"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\SadCatClown.tga:32:32",
    ["FRICK"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\FRICK.tga:32:32",
    ["CEASE"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\CEASE.tga:32:32",
    ["sputWide"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\sputWide.tga:32:84",
    ["lookDown"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\lookDown.tga:32:32",
    ["lookUp"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\lookUp.tga:32:32",
    ["CRIKEN"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\CRIKEN.tga:32:27",
    ["SoyR"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\SoyR.tga:24:32",
    ["WHOLETHIMCOOK"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\WHOLETHIMCOOK.tga:24:27",
    ["THESTAFF"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\THESTAFF.tga",
    ["devious"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\devious.tga",
    ["RightThere"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\RightThere.tga",
    ["LetMeIn"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\LetMeIn.tga",
    ["CatAHomie"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\CatAHomie.tga",
    ["LockedIn"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\LockedIn.tga",
    ["AAAA"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\AAAA.tga",
    ["petbabey"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\petbabey.tga",
    ["babey"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\babey.tga:28:28",
    ["WAGWHA"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\WAGWHA.tga:32:33",
    ["Sigh"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Sigh.tga:32:32",
    ["pregWan"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\pregWan.tga:32:32",
    ["OneGuy"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\OneGuy.tga:29.5:96",
    ["o7"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\o7.tga:32:40",
    ["mweee"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\mweee.tga:32:33",
    ["Lurkin"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Lurkin.tga:32:32",
    ["glorpWide"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpWide.tga:32:84",
    ["glorpOff"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpOff.tga:32:32",
    ["catFU"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\catFU.tga:32:36",
    ["FeelsPeonMan"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\FeelsPeonMan.tga:32:32",
    ["FOOTMEN"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\FOOTMEN.tga:32:51",
    ["Illident"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Illident.tga:32:32",
    ["yummers"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\yummers.tga:32:32",
    ["Zuggers"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Zuggers.tga:32:32",
    ["mekkaNerdge"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\mekkaNerdge.tga:48:48",
    ["nothKEK"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\nothKEK.tga:48:48",
    ["ligCraft"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\ligCraft.tga:48:48",
    ["wingsCozy"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\wingsCozy.tga:48:48",
    ["FloorDragon"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\FloorDragon.tga:48:96",
    ["deadJeb"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\deadJeb.tga:48:48",
    ["kaneiTea"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\kaneiTea.tga:48:48",
    ["meowchNya"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\meowchNya.tga:48:48",
    ["razorBrewmaster"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\razorBrewmaster.tga:48:48",
    ["landrickTank"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\landrickTank.tga:48:48",
    ["kromSummon"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\kromSummon.tga:48:48",
    ["tifCheer"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\tifCheer.tga:48:48",
    ["WAITWAITWAIT"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\WAITWAITWAIT.tga",
    ["GAGAGA"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\GAGAGA.tga",
    ["glorpDH"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpDH.tga:32:32",
    ["glorpDK"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpDK.tga:32:32",
    ["glorpDR"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpDR.tga:32:32",
    ["glorpDrakB"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpDrakB.tga:32:32",
    ["glorpDrakG"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpDrakG.tga:32:32",
    ["glorpDrakR"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpDrakR.tga:32:32",
    ["glorpDrakY"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpDrakY.tga:32:32",
    ["glorpDruid"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpDruid.tga:32:32",
    ["glorpEle"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpEle.tga:32:32",
    ["glorpMage"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpMage.tga:32:32",
    ["glorpPriest"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpPriest.tga:32:32",
    ["glorpRogue"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpRogue.tga:32:32",
    ["glorpWarlock"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpWarlock.tga:32:32",
    ["glorpWarrior"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpWarrior.tga:32:32",
    ["glorpWW"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpWW.tga:32:32",
    ["hiii"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\hiii.tga",
    ["byeee"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\byeee.tga",
    ["feaky"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\feaky.tga:32:96",
    ["Deplete"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Deplete.tga",
    ["mee"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\mee.tga",
    ["Tastyge"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Tastyge.tga",
    ["IRIE"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\IRIE.tga",
    ["WAGWAN"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\WAGWAN.tga",
    ["lildans"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\lildans.tga",
    ["StoryTime"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\StoryTime.tga",
    ["GIGATAUREN"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\GIGATAUREN.tga",
    ["blalalatath"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\blalalatath.tga",
    ["JAMMIES"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\JAMMIES.tga",
    ["Joel"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Joel.tga",
    ["poggSpin"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\poggSpin.tga",
    ["HotBois"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\HotBois.tga",
    ["POGWAN"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\POGWAN.tga:32:32",
    ["SCATTER"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\SCATTER.tga",
    ["alooo"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\alooo.tga:32:32",
    ["bejj"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\bejj.tga:32:32",
    ["blushh"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\blushh.tga:32:32",
    ["bukWide"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\bukWide.tga:32:84",
    ["businejj"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\businejj.tga:32:32",
    ["CHARBORG"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\CHARBORG.tga:32:31",
    ["charboWide"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\charboWide.tga:32:84",
    ["chatWide"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\chatWide.tga:32:84",
    ["cheifWide"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\cheifWide.tga:32:84",
    ["cozii"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\cozii.tga:32:32",
    ["crikWide"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\crikWide.tga:32:84",
    ["Egads"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Egads.tga:32:32",
    ["ezz"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\ezz.tga:32:32",
    ["fishh"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\fishh.tga:32:32",
    ["fricc"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\fricc.tga:32:32",
    ["blesss"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\blesss.tga:32:59",
    ["goodd"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\goodd.tga:32:35",
    ["hugg"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\hugg.tga:32:32",
    ["Joelver"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Joelver.tga:32:32",
    ["Cupcake"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Cupcake.tga:32:32",
    ["nise"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\nise.tga:32:34",
    ["nohear"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\nohear.tga:32:32",
    ["nolook"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\nolook.tga:32:30",
    ["notnise"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\notnise.tga:32:34",
    ["pizz"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\pizz.tga:32:34",
    ["poutt"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\poutt.tga:32:32",
    ["Purge"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Purge.tga:32:24",
    ["sitt"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\sitt.tga:32:32",
    ["Sludge"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Sludge.tga:32:58",
    ["staree"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\staree.tga:32:32",
    ["tink"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\tink.tga:32:32",
    ["wikked"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\wikked.tga:32:32",
    ["woboWide"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\woboWide.tga:32:84",
    ["workWork"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\workWork.tga:32:32",
    ["Wormtongue"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Wormtongue.tga:32:53",
    ["awaree"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\awaree.tga",
    ["chadd"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\chadd.tga",
    ["charboDance"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\charboDance.tga",
    ["crikWalk"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\crikWalk.tga",
    ["CYBERBULLYING"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\CYBERBULLYING.tga",
    ["danse"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\danse.tga",
    ["dramaa"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\dramaa.tga",
    ["EvilJoel"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\EvilJoel.tga",
    ["ewLeague"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\ewLeague.tga",
    ["GAMBAADDICT"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\GAMBAADDICT.tga",
    ["GIGADEAD"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\GIGADEAD.tga",
    ["gigl"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\gigl.tga",
    ["glorpArrive"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpArrive.tga",
    ["glorpLeave"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpLeave.tga",
    ["HyperRollCAT"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\HyperRollCAT.tga",
    ["notee"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\notee.tga",
    ["oljj"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\oljj.tga",
    ["ono"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\ono.tga",
    ["panicc"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\panicc.tga",
    ["PeakPls"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\PeakPls.tga",
    ["peepoArrive"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\peepoArrive.tga",
    ["peepoLate"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\peepoLate.tga",
    ["peepoLeave"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\peepoLeave.tga",
    ["peepoTalk"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\peepoTalk.tga",
    ["Poor"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Poor.tga",
    ["riott"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\riott.tga",
    ["scrajj"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\scrajj.tga",
    ["singg"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\singg.tga",
    ["taurenPls"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\taurenPls.tga",
    ["theyWorm"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\theyWorm.tga",
    ["tuckk"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\tuckk.tga",
    ["verypogg"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\verypogg.tga",
    ["wowTime"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\wowTime.tga",
    ["woww"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\woww.tga",
    ["DESKCHAN"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\DESKCHAN.tga",
    ["PROGGERS"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\PROGGERS.tga:32:32",
    ["Gludge"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Gludge.tga:32:58",
    ["PLACE"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\PLACE.tga:32:40",
    ["ewwLeague"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\ewwLeague.tga",
    ["Muted"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\muted.tga",
    ["LL"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\LL.tga",
    ["HACKERMAN"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\HACKERMAN.tga",
    ["happ"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\happ.tga:32:32",
    ["owo7"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\owo7.tga:32:47",
    ["hehe"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\hehe.tga:32:32",
    ["nothBoom"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\nothBoom.tga",
    ["zhikDevious"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\zhikDevious.tga:48:48",
    ["thorGuildLead"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\thorGuildLead.tga:48:48",
    ["aivyHOA"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\aivyHOA.tga:48:48",
    ["ayaCorpa"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\ayaCorpa.tga:48:48",
    ["harperPuppy"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\harperPuppy.tga:48:48",
    ["milliyBadCall"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\milliyBadCall.tga:48:48",
    ["ryaiuBenched"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\ryaiuBenched.tga:48:48",
    ["ryaiuUnbenched"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\ryaiuUnbenched.tga:48:48",
    ["triskHeals"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\triskHeals.tga:48:48",
    ["mekkaGun"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\mekkaGun.tga:48:48",
    ["henrySCREECH"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\henrySCREECH.tga:48:48",
    ["SamFREAKY1"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\SamFREAKY1.tga",
    ["Melons"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Melons.tga",
    ["sputMelonsWide"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\sputMelonsWide.tga",
    ["fu"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\fu.tga",
    ["ooBLEH"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\ooBLEH.tga",
    ["AINTNOWAY"] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\AINTNOWAY.tga",
    [""] = "Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\.tga",
}

--[[
Animation Metadata Table

For each animated emote, define:
- nFrames: Number of frames in the sprite sheet
- frameWidth: Width of each frame in pixels
- frameHeight: Height of each frame in pixels (typically 32)
- imageWidth: Total image width (must be power of 2 >= frameWidth)
- imageHeight: Total image height (must be power of 2 >= nFrames * frameHeight)
- framerate: Playback speed in frames per second
- pingpong: (optional) If true, animation plays forward then backward

For non-square emotes, frameWidth and frameHeight can differ.
The display will automatically scale to preserve aspect ratio.

See Animator.lua for detailed instructions on creating animated emotes.
]]
TwitchEmotes_Baddies_Animation_Metadata = {
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\AAAA.tga"] = {nFrames = 7, frameWidth = 32, frameHeight = 32, imageWidth = 32, imageHeight = 256, framerate = 30},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\OhSnap.tga"] = {nFrames = 29, frameWidth = 56, frameHeight = 56, imageWidth = 56, imageHeight = 1624, framerate = 12.5},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\mhm.tga"] = {nFrames = 9, frameWidth = 74, frameHeight = 64, imageWidth = 74, imageHeight = 576, framerate = 5},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\GLORPSHIT.tga"] = {nFrames = 75, frameWidth = 92, frameHeight = 64, imageWidth = 92, imageHeight = 4800, framerate = 33.33},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Shoo.tga"] = {nFrames = 45, frameWidth = 74, frameHeight = 64, imageWidth = 74, imageHeight = 2880, framerate = 16},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\NOOOO.tga"] = {nFrames = 6, frameWidth = 102, frameHeight = 96, imageWidth = 102, imageHeight = 576, framerate = 33},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\yippee.tga"] = {nFrames = 35, frameWidth = 96, frameHeight = 96, imageWidth = 96, imageHeight = 3360, framerate = 20},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\clappi.tga"] = {nFrames = 29, frameWidth = 168, frameHeight = 96, imageWidth = 168, imageHeight = 2784, framerate = 33},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\THESTAFF.tga"] = {nFrames = 32, frameWidth = 96, frameHeight = 96, imageWidth = 96, imageHeight = 3072, framerate = 8},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\devious.tga"] = {nFrames = 21, frameWidth = 96, frameHeight = 96, imageWidth = 96, imageHeight = 2016, framerate = 25},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\RightThere.tga"] = {nFrames = 56, frameWidth = 111, frameHeight = 96, imageWidth = 111, imageHeight = 5376, framerate = 25},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\LetMeIn.tga"] = {nFrames = 46, frameWidth = 96, frameHeight = 96, imageWidth = 96, imageHeight = 4416, framerate = 20},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\CatAHomie.tga"] = {nFrames = 20, frameWidth = 105, frameHeight = 96, imageWidth = 105, imageHeight = 1920, framerate = 10},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\LockedIn.tga"] = {nFrames = 18, frameWidth = 105, frameHeight = 96, imageWidth = 105, imageHeight = 1728, framerate = 10},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\petbabey.tga"] = {nFrames = 5, frameWidth = 112, frameHeight = 112, imageWidth = 112, imageHeight = 560, framerate = 14},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\WAITWAITWAIT.tga"] = {nFrames = 64, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 4096, framerate = 25},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\GAGAGA.tga"] = {nFrames = 11, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 704, framerate = 19.3},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\hiii.tga"] = {nFrames = 8, frameWidth = 96, frameHeight = 32, imageWidth = 96, imageHeight = 256, framerate = 50},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\byeee.tga"] = {nFrames = 20, frameWidth = 96, frameHeight = 32, imageWidth = 96, imageHeight = 640, framerate = 33.33},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Deplete.tga"] = {nFrames = 14, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 896, framerate = 7},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\sputSussy.tga"] = {nFrames = 6, frameWidth = 112, frameHeight = 112, imageWidth = 112, imageHeight = 672, framerate = 10},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\mee.tga"] = {nFrames = 70, frameWidth = 48, frameHeight = 64, imageWidth = 48, imageHeight = 4480, framerate = 25.93},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Tastyge.tga"] = {nFrames = 120, frameWidth = 88, frameHeight = 64, imageWidth = 88, imageHeight = 7680, framerate = 33.33},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\IRIE.tga"] = {nFrames = 150, frameWidth = 90, frameHeight = 64, imageWidth = 90, imageHeight = 9600, framerate = 29.94},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\WAGWAN.tga"] = {nFrames = 149, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 9536, framerate = 33.33},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\lildans.tga"] = {nFrames = 121, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 7744, framerate = 26.89},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\StoryTime.tga"] = {nFrames = 50, frameWidth = 92, frameHeight = 64, imageWidth = 92, imageHeight = 3200, framerate = 50},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\GIGATAUREN.tga"] = {nFrames = 144, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 9216, framerate = 25},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\blalalatath.tga"] = {nFrames = 2, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 128, framerate = 16.666},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\JAMMIES.tga"] = {nFrames = 123, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 7872, framerate = 25},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Joel.tga"] = {nFrames = 36, frameWidth = 96, frameHeight = 32, imageWidth = 128, imageHeight = 2048, framerate = 15},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\poggSpin.tga"] = {nFrames = 6, frameWidth = 32, frameHeight = 32, imageWidth = 32, imageHeight = 256, framerate = 15},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\HotBois.tga"] = {nFrames = 19, frameWidth = 32, frameHeight = 32, imageWidth = 32, imageHeight = 1024, framerate = 15},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\SCATTER.tga"] = {nFrames = 14, frameWidth = 192, frameHeight = 48, imageWidth = 192, imageHeight = 672, framerate = 16.67},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\awaree.tga"] = {nFrames = 12, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 768, framerate = 5.71},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\chadd.tga"] = {nFrames = 56, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 3584, framerate = 10},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\charboDance.tga"] = {nFrames = 63, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 4032, framerate = 11.49},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\crikWalk.tga"] = {nFrames = 79, frameWidth = 66, frameHeight = 64, imageWidth = 66, imageHeight = 5056, framerate = 30.03},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\CYBERBULLYING.tga"] = {nFrames = 10, frameWidth = 164, frameHeight = 64, imageWidth = 164, imageHeight = 640, framerate = 19.23},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\danse.tga"] = {nFrames = 6, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 384, framerate = 2.85},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\dramaa.tga"] = {nFrames = 4, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 256, framerate = 2},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\EvilJoel.tga"] = {nFrames = 36, frameWidth = 192, frameHeight = 64, imageWidth = 192, imageHeight = 2304, framerate = 25.35},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\ewLeague.tga"] = {nFrames = 67, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 4288, framerate = 10},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\GAMBAADDICT.tga"] = {nFrames = 23, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 1472, framerate = 14.28},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\GIGADEAD.tga"] = {nFrames = 129, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 8256, framerate = 16.53},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\gigl.tga"] = {nFrames = 10, frameWidth = 70, frameHeight = 64, imageWidth = 70, imageHeight = 640, framerate = 50},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpArrive.tga"] = {nFrames = 100, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 6400, framerate = 31.84},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\glorpLeave.tga"] = {nFrames = 100, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 6400, framerate = 50},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\HyperRollCAT.tga"] = {nFrames = 33, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 2112, framerate = 50},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\notee.tga"] = {nFrames = 57, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 3648, framerate = 33.33},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\oljj.tga"] = {nFrames = 12, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 768, framerate = 5.71},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\ono.tga"] = {nFrames = 48, frameWidth = 94, frameHeight = 64, imageWidth = 94, imageHeight = 3072, framerate = 28.07},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\panicc.tga"] = {nFrames = 10, frameWidth = 82, frameHeight = 64, imageWidth = 82, imageHeight = 640, framerate = 16.66},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\PeakPls.tga"] = {nFrames = 28, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 1792, framerate = 16.56},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\peepoArrive.tga"] = {nFrames = 33, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 2112, framerate = 10},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\peepoLate.tga"] = {nFrames = 11, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 704, framerate = 3.33},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\peepoLeave.tga"] = {nFrames = 29, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 1856, framerate = 8.28},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\peepoTalk.tga"] = {nFrames = 71, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 4544, framerate = 16.66},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\Poor.tga"] = {nFrames = 98, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 6272, framerate = 25},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\riott.tga"] = {nFrames = 4, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 256, framerate = 5},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\scrajj.tga"] = {nFrames = 2, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 128, framerate = 8.33},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\singg.tga"] = {nFrames = 2, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 128, framerate = 2.85},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\taurenPls.tga"] = {nFrames = 26, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 1664, framerate = 16.66},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\theyWorm.tga"] = {nFrames = 3, frameWidth = 94, frameHeight = 64, imageWidth = 94, imageHeight = 192, framerate = 10},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\tuckk.tga"] = {nFrames = 6, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 384, framerate = 5},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\verypogg.tga"] = {nFrames = 16, frameWidth = 68, frameHeight = 64, imageWidth = 68, imageHeight = 1024, framerate = 12.59},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\wowTime.tga"] = {nFrames = 71, frameWidth = 128, frameHeight = 64, imageWidth = 128, imageHeight = 4544, framerate = 18.68},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\woww.tga"] = {nFrames = 2, frameWidth = 70, frameHeight = 64, imageWidth = 70, imageHeight = 128, framerate = 5},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\DESKCHAN.tga"] = {nFrames = 15, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 960, framerate = 50},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\ewwLeague.tga"] = {nFrames = 53, frameWidth = 112, frameHeight = 112, imageWidth = 112, imageHeight = 5936, framerate = 12.01},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\muted.tga"] = {nFrames = 25, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 1600, framerate = 20},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\LL.tga"] = {nFrames = 20, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 1280, framerate = 33.33},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\HACKERMAN.tga"] = {nFrames = 11, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 704, framerate = 20},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\nothBoom.tga"] = {nFrames = 33, frameWidth = 128, frameHeight = 128, imageWidth = 128, imageHeight = 4224, framerate = 16.5},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\SamFREAKY1.tga"] = {nFrames = 6, frameWidth = 112, frameHeight = 112, imageWidth = 112, imageHeight = 672, framerate = 27.27},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\ooBLEH.tga"] = {nFrames = 82, frameWidth = 190, frameHeight = 64, imageWidth = 190, imageHeight = 5248, framerate = 30.71},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\AINTNOWAY.tga"] = {nFrames = 200, frameWidth = 78, frameHeight = 64, imageWidth = 78, imageHeight = 12800, framerate = 32.52},
    ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\.tga"] = {nFrames = 11, frameWidth = 64, frameHeight = 64, imageWidth = 64, imageHeight = 704, framerate = 20},
    -- ["Interface\\AddOns\\TwitchEmotes_Baddies\\emotes\\example.tga"] = {
    --     nFrames = 24, < Number of frames in the gif
    --     frameWidth = 32, < width of the gif
    --     frameHeight = 32, < height of the gif
    --     imageWidth = 32, < width of the sprite sheet
    --     imageHeight = 1024, < height of the sprite sheet
    --     framerate = 15, < number of frames divided by length of gif
    -- },
}
